### ISSUE TITLE
Include opossum tools into the UI and allow opening more file formats

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1485] opened 2023-03-14 15:57 UTC
## Context

Currently the Opossum UI can open and work only with limited number of file formats: .opossum, opossum.json and .json.gz.

## Idea

It would be nice to support usage of other formats, e.g. spdx or scancode, by including some opossum tools into the app, e.g. haskell tool (https://github.com/opossum-tool/opossum.lib.hs).
Maybe also add --opossum flag to ScanCode.

Bonus: Allow open/merge/import several files.

**Comment by mstykow** [comment] 2024-03-05 12:38
Duplicate of #1592

**Closed by mstykow** 2024-03-05 12:38 UTC
Labels: enhancement
