### ISSUE TITLE
There should be "going back" button for resource tree

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#981] opened 2022-09-13 07:37 UTC
As a user I would like to be able to navigate back to the previously visited resource.
This could be implemented by adding "go back" button for the resource tree, menu item and a shortcut.

**Comment by mstykow** [comment] 2023-11-16 07:59
Duplicate of #2299

**Closed by mstykow** 2023-11-16 07:59 UTC
Labels: enhancement
